export const INGREDIENT_EMOJI_OPTIONS: { emoji: string; label: string }[] = [
  { emoji: '🧄', label: 'Beli luk' },
  { emoji: '🧅', label: 'Crni luk' },
  { emoji: '🥔', label: 'Krompir' },
  { emoji: '🥕', label: 'Šargarepa' },
  { emoji: '🍅', label: 'Paradajz' },
  { emoji: '🫑', label: 'Paprika' },
  { emoji: '🌶️', label: 'Aleva paprika' },
  { emoji: '🥬', label: 'Lisnato povrće' },
  { emoji: '🥦', label: 'Brokoli' },
  { emoji: '🌽', label: 'Kukuruz' },
  { emoji: '🍄', label: 'Pečurke' },
  { emoji: '🍆', label: 'Patlidžan' },
  { emoji: '🥒', label: 'Krastavac' },
  { emoji: '🎃', label: 'Bundeva' },
  { emoji: '🥑', label: 'Avokado' },
  { emoji: '🍋', label: 'Limun' },
  { emoji: '🍊', label: 'Narandža' },
  { emoji: '🍎', label: 'Jabuka' },
  { emoji: '🍌', label: 'Banana' },
  { emoji: '🍇', label: 'Grožđe' },
  { emoji: '🍓', label: 'Jagoda' },
  { emoji: '🍒', label: 'Višnja' },
  { emoji: '🍑', label: 'Breskva' },
  { emoji: '🫐', label: 'Borovnica' },
  { emoji: '🫒', label: 'Masline' },
  { emoji: '🫙', label: 'Tegla' },
  { emoji: '🧂', label: 'So i biber' },
  { emoji: '🌿', label: 'Začinsko bilje' },
  { emoji: '🍃', label: 'Lovor' },
  { emoji: '🟤', label: 'Cimet' },
  { emoji: '🟡', label: 'Kurkuma' },
  { emoji: '🫚', label: 'Đumbir' },
  { emoji: '🧊', label: 'Kocka za supu' },
  { emoji: '🥩', label: 'Meso' },
  { emoji: '🍗', label: 'Piletina' },
  { emoji: '🥓', label: 'Slanina' },
  { emoji: '🌭', label: 'Kobasica' },
  { emoji: '🐟', label: 'Riba' },
  { emoji: '🦐', label: 'Škampi' },
  { emoji: '🫘', label: 'Pasulj' },
  { emoji: '🫛', label: 'Grašak' },
  { emoji: '🍚', label: 'Pirinač' },
  { emoji: '🍝', label: 'Testenina' },
  { emoji: '🌮', label: 'Tortilja' },
  { emoji: '🌾', label: 'Brašno' },
  { emoji: '🍞', label: 'Hleb' },
  { emoji: '🥐', label: 'Pecivo' },
  { emoji: '🧀', label: 'Sir' },
  { emoji: '🥚', label: 'Jaja' },
  { emoji: '🥛', label: 'Mleko' },
  { emoji: '🧈', label: 'Puter' },
  { emoji: '🥫', label: 'Konzerva' },
  { emoji: '🍯', label: 'Med' },
  { emoji: '🍬', label: 'Šećer' },
  { emoji: '🍫', label: 'Čokolada' },
  { emoji: '☕', label: 'Kafa' },
  { emoji: '🍵', label: 'Čaj' },
  { emoji: '💧', label: 'Voda' },
  { emoji: '🍷', label: 'Vino' },
  { emoji: '🍺', label: 'Pivo' },
  { emoji: '🌰', label: 'Orah' },
  { emoji: '🥜', label: 'Kikiriki' },
];

const INGREDIENT_EMOJI_KEYWORDS: [string, string][] = [
  ['beli luk', '🧄'],
  ['belog luka', '🧄'],
  ['belom luku', '🧄'],
  ['bijeli luk', '🧄'],
  ['bijelog luka', '🧄'],
  ['češnjak', '🧄'],
  ['cesnjak', '🧄'],
  ['crni luk', '🧅'],
  ['crnog luka', '🧅'],
  ['crnom luku', '🧅'],
  ['crveni luk', '🧅'],
  ['crvenog luka', '🧅'],
  ['luk', '🧅'],
  ['luka', '🧅'],
  ['luku', '🧅'],
  ['krompir', '🥔'],
  ['krompira', '🥔'],
  ['krumpir', '🥔'],
  ['krumpira', '🥔'],
  ['batat', '🥔'],
  ['krompirov skrob', '🥔'],
  ['šargarepa', '🥕'],
  ['šargarepe', '🥕'],
  ['sargarepa', '🥕'],
  ['mrkva', '🥕'],
  ['mrkve', '🥕'],
  ['paradajz', '🍅'],
  ['paradajza', '🍅'],
  ['rajčica', '🍅'],
  ['rajcica', '🍅'],
  ['pelat', '🍅'],
  ['kečap', '🍅'],
  ['kecap', '🍅'],
  ['ketchup', '🍅'],
  ['aleva paprika', '🌶️'],
  ['aleve paprike', '🌶️'],
  ['crvena paprika', '🌶️'],
  ['ljuta paprika', '🌶️'],
  ['mlevena paprika', '🌶️'],
  ['mljevena paprika', '🌶️'],
  ['čili', '🌶️'],
  ['cili', '🌶️'],
  ['feferon', '🌶️'],
  ['feferoni', '🌶️'],
  ['babura', '🫑'],
  ['ajvar', '🫑'],
  ['paprika', '🫑'],
  ['kiseli kupus', '🥬'],
  ['zelena salata', '🥬'],
  ['kupus', '🥬'],
  ['kupusa', '🥬'],
  ['kelj', '🥬'],
  ['spanać', '🥬'],
  ['spanac', '🥬'],
  ['špinat', '🥬'],
  ['spinat', '🥬'],
  ['blitva', '🥬'],
  ['salata', '🥬'],
  ['praziluk', '🥬'],
  ['poriluk', '🥬'],
  ['celer', '🥬'],
  ['celera', '🥬'],
  ['brokoli', '🥦'],
  ['karfiol', '🥦'],
  ['cvjetača', '🥦'],
  ['cvjetaca', '🥦'],
  ['kukuruz', '🌽'],
  ['kukuruza', '🌽'],
  ['palenta', '🌽'],
  ['pečurke', '🍄'],
  ['pečurka', '🍄'],
  ['pecurke', '🍄'],
  ['šampinjon', '🍄'],
  ['sampinjon', '🍄'],
  ['gljive', '🍄'],
  ['gljiva', '🍄'],
  ['patlidžan', '🍆'],
  ['krastavac', '🥒'],
  ['krastavca', '🥒'],
  ['tikvica', '🥒'],
  ['tikvice', '🥒'],
  ['cukini', '🥒'],
  ['kornišon', '🥒'],
  ['kornison', '🥒'],
  ['bundeva', '🎃'],
  ['tikva', '🎃'],
  ['avokado', '🥑'],
  ['limun', '🍋'],
  ['limuna', '🍋'],
  ['narandža', '🍊'],
  ['naranča', '🍊'],
  ['naranca', '🍊'],
  ['pomorandža', '🍊'],
  ['mandarina', '🍊'],
  ['jabuka', '🍎'],
  ['jabuke', '🍎'],
  ['banana', '🍌'],
  ['banane', '🍌'],
  ['grožđe', '🍇'],
  ['grozdje', '🍇'],
  ['jagoda', '🍓'],
  ['jagode', '🍓'],
  ['malina', '🍓'],
  ['maline', '🍓'],
  ['višnja', '🍒'],
  ['visnja', '🍒'],
  ['trešnja', '🍒'],
  ['tresnja', '🍒'],
  ['breskva', '🍑'],
  ['kajsija', '🍑'],
  ['borovnica', '🫐'],
  ['borovnice', '🫐'],
  ['maslinovo ulje', '🫒'],
  ['maslinovog ulja', '🫒'],
  ['masline', '🫒'],
  ['maslina', '🫒'],
  ['soja sos', '🫙'],
  ['sojin sos', '🫙'],
  ['sos od soje', '🫙'],
  ['jabukovo sirće', '🫙'],
  ['suncokretovo ulje', '🫙'],
  ['sirće', '🫙'],
  ['sirćeta', '🫙'],
  ['ocat', '🫙'],
  ['octa', '🫙'],
  ['ulje', '🫙'],
  ['ulja', '🫙'],
  ['majonez', '🫙'],
  ['majoneza', '🫙'],
  ['sos', '🫙'],
  ['so', '🧂'],
  ['sol', '🧂'],
  ['soli', '🧂'],
  ['biber', '🧂'],
  ['bibera', '🧂'],
  ['papar', '🧂'],
  ['vegeta', '🧂'],
  ['bosiljak', '🌿'],
  ['peršun', '🌿'],
  ['persun', '🌿'],
  ['peršin', '🌿'],
  ['origano', '🌿'],
  ['kumin', '🌿'],
  ['kim', '🌿'],
  ['mirođija', '🌿'],
  ['mirodjija', '🌿'],
  ['kopar', '🌿'],
  ['ruzmarin', '🌿'],
  ['ružmarin', '🌿'],
  ['timijan', '🌿'],
  ['nana', '🌿'],
  ['menta', '🌿'],
  ['korijander', '🌿'],
  ['vanila', '🌿'],
  ['vanilin', '🌿'],
  ['hren', '🌿'],
  ['ren', '🌿'],
  ['lovor', '🍃'],
  ['cimet', '🟤'],
  ['cimeta', '🟤'],
  ['kurkuma', '🟡'],
  ['kari', '🟡'],
  ['senf', '🟡'],
  ['đumbir', '🫚'],
  ['dumbir', '🫚'],
  ['djumbir', '🫚'],
  ['goveđa kocka', '🧊'],
  ['supena kocka', '🧊'],
  ['kocka za supu', '🧊'],
  ['mleveno meso', '🥩'],
  ['mljeveno meso', '🥩'],
  ['mlevenog mesa', '🥩'],
  ['mljevenog mesa', '🥩'],
  ['meso', '🥩'],
  ['mesa', '🥩'],
  ['govedina', '🥩'],
  ['junetina', '🥩'],
  ['svinjetina', '🥩'],
  ['teletina', '🥩'],
  ['jagnjetina', '🥩'],
  ['piletina', '🍗'],
  ['piletine', '🍗'],
  ['pileći', '🍗'],
  ['pileci', '🍗'],
  ['pileća', '🍗'],
  ['pileca', '🍗'],
  ['pile', '🍗'],
  ['ćuretina', '🍗'],
  ['curetina', '🍗'],
  ['slanina', '🥓'],
  ['pršuta', '🥓'],
  ['prsuta', '🥓'],
  ['panceta', '🥓'],
  ['kobasica', '🌭'],
  ['kobasice', '🌭'],
  ['viršla', '🌭'],
  ['virsla', '🌭'],
  ['hrenovka', '🌭'],
  ['kulen', '🌭'],
  ['riba', '🐟'],
  ['ribe', '🐟'],
  ['oslić', '🐟'],
  ['oslic', '🐟'],
  ['losos', '🐟'],
  ['tuna', '🐟'],
  ['tunjevina', '🐟'],
  ['sardina', '🐟'],
  ['sardine', '🐟'],
  ['škampi', '🦐'],
  ['skampi', '🦐'],
  ['gambori', '🦐'],
  ['pasulj', '🫘'],
  ['pasulja', '🫘'],
  ['grah', '🫘'],
  ['graha', '🫘'],
  ['boranija', '🫘'],
  ['sočivo', '🫘'],
  ['socivo', '🫘'],
  ['leća', '🫘'],
  ['leca', '🫘'],
  ['leblebija', '🫘'],
  ['slanutak', '🫘'],
  ['naut', '🫘'],
  ['soja', '🫘'],
  ['soje', '🫘'],
  ['grašak', '🫛'],
  ['graška', '🫛'],
  ['pirinač', '🍚'],
  ['pirinac', '🍚'],
  ['riža', '🍚'],
  ['riza', '🍚'],
  ['kuskus', '🍚'],
  ['kus kus', '🍚'],
  ['špageti', '🍝'],
  ['spageti', '🍝'],
  ['testenina', '🍝'],
  ['testenine', '🍝'],
  ['makarone', '🍝'],
  ['rezanci', '🍝'],
  ['jufka', '🍝'],
  ['tortilja', '🌮'],
  ['tortilje', '🌮'],
  ['brašno', '🌾'],
  ['brasno', '🌾'],
  ['brašna', '🌾'],
  ['griz', '🌾'],
  ['ovas', '🌾'],
  ['zob', '🌾'],
  ['kvasac', '🌾'],
  ['skrob', '🌾'],
  ['hleb', '🍞'],
  ['hleba', '🍞'],
  ['kruh', '🍞'],
  ['kruha', '🍞'],
  ['prezle', '🍞'],
  ['prezla', '🍞'],
  ['kifla', '🥐'],
  ['kiflice', '🥐'],
  ['pecivo', '🥐'],
  ['kačkavalj', '🧀'],
  ['kackavalj', '🧀'],
  ['parmezan', '🧀'],
  ['mocarela', '🧀'],
  ['mozzarella', '🧀'],
  ['feta', '🧀'],
  ['gauda', '🧀'],
  ['trapist', '🧀'],
  ['kajmak', '🧀'],
  ['kajmaka', '🧀'],
  ['sir', '🧀'],
  ['sira', '🧀'],
  ['jaje', '🥚'],
  ['jaja', '🥚'],
  ['jaju', '🥚'],
  ['kiselo mleko', '🥛'],
  ['kisela pavlaka', '🥛'],
  ['mleko', '🥛'],
  ['mleka', '🥛'],
  ['mlijeko', '🥛'],
  ['mlijeka', '🥛'],
  ['jogurt', '🥛'],
  ['jogurta', '🥛'],
  ['pavlaka', '🥛'],
  ['pavlake', '🥛'],
  ['vrhnje', '🥛'],
  ['mileram', '🥛'],
  ['puter', '🧈'],
  ['putera', '🧈'],
  ['maslac', '🧈'],
  ['maslaca', '🧈'],
  ['konzerva', '🥫'],
  ['med', '🍯'],
  ['meda', '🍯'],
  ['džem', '🍯'],
  ['dzem', '🍯'],
  ['pekmez', '🍯'],
  ['marmelada', '🍯'],
  ['šećer', '🍬'],
  ['secer', '🍬'],
  ['šećera', '🍬'],
  ['secera', '🍬'],
  ['čokolada', '🍫'],
  ['cokolada', '🍫'],
  ['kakao', '🍫'],
  ['kafa', '☕'],
  ['kave', '☕'],
  ['kava', '☕'],
  ['čaj', '🍵'],
  ['caj', '🍵'],
  ['voda', '💧'],
  ['vode', '💧'],
  ['vino', '🍷'],
  ['vina', '🍷'],
  ['pivo', '🍺'],
  ['piva', '🍺'],
  ['orah', '🌰'],
  ['oraha', '🌰'],
  ['orasi', '🌰'],
  ['lešnik', '🌰'],
  ['lesnik', '🌰'],
  ['badem', '🌰'],
  ['bademi', '🌰'],
  ['kikiriki', '🥜'],
];

function emojiKey(value: string): string {
  return value.replace(/\uFE0F/g, '');
}

const CANONICAL_BY_KEY = new Map(
  INGREDIENT_EMOJI_OPTIONS.map((option) => [emojiKey(option.emoji), option.emoji])
);

function foldLetters(value: string): string {
  return value
    .toLowerCase()
    .replace(/đ/g, 'dj')
    .replace(/č/g, 'c')
    .replace(/ć/g, 'c')
    .replace(/š/g, 's')
    .replace(/ž/g, 'z');
}

function ingredientWords(value: string): string[] {
  return foldLetters(value)
    .split(/[^a-z0-9]+/)
    .filter(Boolean);
}

const PREPARED_KEYWORDS = INGREDIENT_EMOJI_KEYWORDS.map(([keyword, emoji]) => ({
  words: ingredientWords(keyword),
  emoji,
  length: foldLetters(keyword).replace(/\s+/g, ' ').trim().length,
}))
  .filter((entry) => entry.words.length > 0)
  .sort((a, b) => b.length - a.length);

function phraseMatches(words: string[], keywordWords: string[]): boolean {
  if (keywordWords.length === 1) return words.includes(keywordWords[0]);
  for (let start = 0; start <= words.length - keywordWords.length; start += 1) {
    if (keywordWords.every((word, offset) => words[start + offset] === word)) return true;
  }
  return false;
}

export function canonicalIngredientEmoji(value: string | null | undefined): string | null {
  if (!value) return null;
  return CANONICAL_BY_KEY.get(emojiKey(value.trim())) ?? null;
}

export function sameIngredientKey(left: string, right: string): boolean {
  return foldLetters(left.trim()) === foldLetters(right.trim());
}

export function isAllowedIngredientEmoji(value: string | null | undefined): boolean {
  return canonicalIngredientEmoji(value) !== null;
}

export function matchIngredientEmoji(name: string): string | null {
  const words = ingredientWords(name);
  if (words.length === 0) return null;
  for (const entry of PREPARED_KEYWORDS) {
    if (phraseMatches(words, entry.words)) return entry.emoji;
  }
  return null;
}

export function ingredientEmojiPromptLines(): string {
  return INGREDIENT_EMOJI_OPTIONS.map((option) => `${option.emoji} ${option.label}`).join('\n');
}
